# See: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#configuration-options-for-dependabotyml
version: 2
updates:
    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: weekly
      open-pull-requests-limit: 3

    - package-ecosystem: npm
      directory: "/interfaces/IBF-dashboard"
      schedule:
          interval: weekly
      open-pull-requests-limit: 3
      versioning-strategy: increase-if-necessary

    - package-ecosystem: docker
      directory: "/interfaces/IBF-dashboard"
      schedule:
          interval: weekly
      open-pull-requests-limit: 3

    - package-ecosystem: npm
      directory: "/services/API-service"
      schedule:
          interval: weekly
      open-pull-requests-limit: 3
      versioning-strategy: increase-if-necessary

    - package-ecosystem: docker
      directory: "/services/API-service"
      schedule:
          interval: weekly
      open-pull-requests-limit: 3
